### ISSUE TITLE
how to render zdepth in cuda code?

### ISSUE THREAD

**Issue by zhw-github** [postech-ami/HDR-Plenoxels#1]
Hi,
I saw on github that you doublet the code of the original author of plenoxels. And see you want to optimize depth. This is relevant to my research.In svox2.py file,define a volume_render_depth function?
I think this code is important:
*out_depth += (weight * ((t / opt.step_size) * ray.world_step);How to change this code to render zdepth?
But the original author said this is the absolute length along the ray, not the z-depth as usually expected.So how should I modify this code to get zdepth!

**Comment by gucka28** [comment]
As you mentioned in the question, we utilized the original code of Plenoxels.
Unfortunately, we did not edit the cuda code separately, but took the code and modified them according our purpose.
For accurate instructions, it would be better to ask and check the Plenoxel original repo.

**Comment by ChenLu-china** [comment]
I am also change the depth code, it is easy to change zdepth to distance.
