### ISSUE TITLE
I can't download the datasets

### ISSUE THREAD

**Issue by sunciliang** [postech-ami/HDR-Plenoxels#4]
https://postechackr-my.sharepoint.com/personal/gucka28_postech_ac_kr/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fgucka28%5Fpostech%5Fac%5Fkr%2FDocuments%2FHDR%2DPlenoxels%5Fdataset&ga=1
this site cannot be accessed, it shows not found in posttechackr-my.sharepoint.com directory.

**Comment by ug-kim** [comment]
Hi, sorry for this.
Please retry with the below link.
If it is also not working, please send mail to Jun-Seong (junseong.kim@postech.ac.kr).

https://postechackr-my.sharepoint.com/:f:/g/personal/gucka28_postech_ac_kr/EiM6SNSIJhRPl908z3zGTRoBxSlcgtejMkVC3eQCHG5ywA?e=vd5TGk

**Comment by ug-kim** [comment]
Hi, sorry for this.
Please retry with the below link.
If it is also not working, please send mail to Jun-Seong (junseong.kim@postech.ac.kr).

https://postechackr-my.sharepoint.com/:f:/g/personal/gucka28_postech_ac_kr/EiM6SNSIJhRPl908z3zGTRoBxSlcgtejMkVC3eQCHG5ywA?e=vd5TGk

**Comment by ug-kim** [comment]
You can also refer this
https://github.com/postech-ami/HDR-Plenoxels/issues/2#issuecomment-1299542411
