### ISSUE TITLE
Link for the dataset is not accessible. 

### ISSUE THREAD

**Issue by MrKarimiD** [postech-ami/HDR-Plenoxels#5]
Hello!

Thanks a lot for sharing your code and data. I cannot access to the dataset using the provided link unfortunately. 

Best,
Mohammad

**Comment by ug-kim** [comment]
Hi, sorry for this.
Please retry with the below link.
If it is also not working, please send mail to Jun-Seong ([junseong.kim@postech.ac.kr](mailto:junseong.kim@postech.ac.kr)).

We will fix this error in the download link soon.

https://postechackr-my.sharepoint.com/:f:/g/personal/gucka28_postech_ac_kr/EiM6SNSIJhRPl908z3zGTRoBxSlcgtejMkVC3eQCHG5ywA?e=vd5TGk

**Comment by ug-kim** [comment]
You can also refer this
https://github.com/postech-ami/HDR-Plenoxels/issues/2#issuecomment-1299542411
