### ISSUE TITLE
Where is camera_camera_modify?

### ISSUE THREAD

**Issue by guanjunwu** [postech-ami/HDR-Plenoxels#6]
Hi! thanks for your great work!
When I am running your code, in file"hdr_render_imgs.py", I got an error called `"can not import cam_param_modify from utils.__init__.py`, it looks like there are no relative function in the code.
But in file `cam_param` , there is a class named "cam_param". However, the class do not have __init__ keywords named "tone_mapping", which trigger another error. When I have deleted the keyword, the results of evluation is wrong. which made me confused.
Could you upload this file "cam_param_modify.py" at your earliest convinence ? thank you!

**Comment by ug-kim** [comment]
Hi,

Please change from `from util import cam_param_motify` to `from util import cam_param`.

If it is not working, please let me know.
`cam_param_motify` is before version of `cam_param` for debugging and `cam_param` is the final version.

**Comment by HiLoveLee** [comment]
Hi, thank you very much for your work
When I followed your method to import from util cam_param_motifyfrom util import cam_param, I found that there is still an issue with the hdr-render_imgs.py script that does not recognize the -- tone mapping parameter.
That is to say, other methods need to be found to specify the desired tone mapping method.
